# Prawdziwa, ucząca się sieć neuronowa

<img src="files/network_241.png" />

In [1]:
# Importujemy bibliotekę numpy (operacje na macierzach)
import numpy as np

# Programowujemy naszą sieć z wykorzystaniem numpy

## Input data

In [1]:
#nasze dane    
dane = np.array([[0,0],
                 [0,1],
                 [1,0],
                 [1,1]])

odpowiedz = np.array([[0],
                      [1],
                      [0],
                      [0]])

NameError: name 'np' is not defined

we switch from indyvidual numbers to matrix based data and network

## Activation function & its derivative

In [4]:
#funkcja aktywacyjna i jej pochodna
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_pochodna(x):
    return x * (1-x)

## Kod implementujący sieć

In [5]:
#funkcje potrzebne do stworzenia sieci
def hidden(j):
    return sigmoid(np.dot(dane[j],Input_Wagi)) #inner product of matricises

def answer(j):
    return sigmoid(np.dot(hidden(j),Hidden_Wagi)) #inner product of matricises

def wagi(seed=True):
    #ustalamy seed, zeby eksperyment byl powtarzalny
    if seed:
        np.random.seed(3)
    #tworzyny losowe wagi za pomoca funkcji numpy (zwraca wartosc pomiedzy 0 i 1)
    Input_Wagi = 2*np.random.random((2,4)) - 1
    Hidden_Wagi = 2*np.random.random((4)) - 1
    return Input_Wagi, Hidden_Wagi

Input_Wagi, Hidden_Wagi = wagi()

print(f'Input_Wagi:\n {Input_Wagi}')
print(f'Hidden_Wagi:\n {Hidden_Wagi}')

Input_Wagi:
 [[ 0.10159581  0.41629565 -0.41819052  0.02165521]
 [ 0.78589391  0.79258618 -0.74882938 -0.58551424]]
Hidden_Wagi:
 [-0.89706559 -0.11838031 -0.94024758 -0.08633355]


# Sieć się uczy

In [7]:
#nasze dane    
dane = np.array([[0,0],
                 [0,1],
                 [1,0],
                 [1,1]])

odpowiedz = np.array([[0],
                      [1],
                      [0],
                      [0]])
epoki = 1000

Input_Wagi, Hidden_Wagi = wagi()

def learn(dane, odpowiedz, Input_Wagi, Hidden_Wagi, epoki, verbose):
    
    errors =  []
    
    for epoch in range(epoki):
        for j in range(4):
            odp = answer(j)
            #print(f' answer: {odp}')
            
            err = []

            answer_error = odpowiedz[j] - odp
            err.append(answer_error)
            
            #print(f'answer error: {answer_error}')
            answer_delta = answer_error*sigmoid_pochodna(odp)
            #print(f'answer_delta: {answer_delta}')
            hidden_error = answer_delta * Hidden_Wagi.T
            #print(f'hidden_error: {hidden_error}')

            hidden_delta = hidden_error * sigmoid_pochodna(hidden(j))
            #print(f'hidden_delta: {hidden_delta}')

            Hidden_Wagi += hidden(j) * (answer_delta)
            #print(f'Hidden_Wagi : {Hidden_Wagi}')

            Input_Wagi += dane[j].reshape(2, 1) * (hidden_delta)
            
            if j == 3:
                err = [abs(i) for i in err]
                errors.append(err)


        if verbose == 1:
            if epoch%(100) == 0:
                for i in range(4):
                    print(f'dane: {dane[i]} odpowiedz: {odpowiedz[i]} odpowiedz_sieci: {answer(i)}')
                print(f'error: {errors[-1][0]}')
                print('-------------------------------------------------------------------')

    return Input_Wagi, Hidden_Wagi

In [8]:
learn(dane, odpowiedz, Input_Wagi, Hidden_Wagi, epoki, verbose = 1)

#decibel value , average error for epoch

dane: [0 0] odpowiedz: [0] odpowiedz_sieci: 0.2591329224206299
dane: [0 1] odpowiedz: [1] odpowiedz_sieci: 0.259739470645977
dane: [1 0] odpowiedz: [0] odpowiedz_sieci: 0.26913528043410406
dane: [1 1] odpowiedz: [0] odpowiedz_sieci: 0.26761473880650216
error: [ 0.28376216]
-------------------------------------------------------------------
dane: [0 0] odpowiedz: [0] odpowiedz_sieci: 0.16174404970211112
dane: [0 1] odpowiedz: [1] odpowiedz_sieci: 0.6870817026404531
dane: [1 0] odpowiedz: [0] odpowiedz_sieci: 0.021720099313901533
dane: [1 1] odpowiedz: [0] odpowiedz_sieci: 0.17302616053475792
error: [ 0.18637754]
-------------------------------------------------------------------
dane: [0 0] odpowiedz: [0] odpowiedz_sieci: 0.09768678532644809
dane: [0 1] odpowiedz: [1] odpowiedz_sieci: 0.8677645096301934
dane: [1 0] odpowiedz: [0] odpowiedz_sieci: 0.002104783993690341
dane: [1 1] odpowiedz: [0] odpowiedz_sieci: 0.06905268625293884
error: [ 0.07041803]
------------------------------------

(array([[ 2.17864477, -1.62033891,  3.965384  ,  1.96399974],
        [-1.89438365,  2.48075202, -2.69429186, -2.10966081]]),
 array([-2.71928825,  4.58576906, -5.62940121, -2.90505642]))

In [9]:
#plot errors in matplotlib

In [10]:
dobre_wagi = learn(dane, odpowiedz, Input_Wagi, Hidden_Wagi, epoki, 0)

In [6]:
dobre_wagi

(array([[ 2.29882376, -1.7897913 ,  4.13320588,  2.09333835],
        [-2.06703959,  2.616031  , -2.83614762, -2.24768868]]),
 array([-3.08072014,  4.96669224, -6.08672886, -3.26791027]))

# Inference

In [11]:
def siec(dobre_wagi, dane):
    
    def sigmoid(x):
        return 1/(1+np.exp(-x))

    def hidden(dane):
        return sigmoid(np.dot(dane,dobre_wagi[0]))

    return sigmoid(np.dot(hidden(dane),dobre_wagi[1]))

    

In [13]:
dane = [0, 0]
siec(dobre_wagi, dane)

0.023331714123759818

#  BackUp

## dot product

In [ ]:
x = np.array([[1,2],[10,20]])
y = np.array([[3,4],[5,6]])
wektor = np.array([2,3])


# Inner product of matrices
#[[1*3+2*5  1*4+2*6], [10*3+20*5 10*4+20*6]
#[13, 16][130, 160]
print(np.dot(x, y))


# Matrix / vector product; produce the rank 1 array [8 80]
#[[2*1+3*2], [2*10 + 3*20]
#[8, 80]
print(np.dot(x, wektor))