## Macierze - tablice

### Biblioteka Numpy

In [1]:
import numpy as np
arr = np.arange(10, 20) . reshape((2,5))


In [2]:
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
arr[1][4]

19

In [4]:
arr.sum()

145

In [5]:
a = np.array([[3, 5, 1], [2, 8,7]])

a.sort()
print(a)

[[1 3 5]
 [2 7 8]]


In [6]:
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:

arr.T

array([[10, 15],
       [11, 16],
       [12, 17],
       [13, 18],
       [14, 19]])

In [18]:
x = np.array([[1,2],[10,20]])
y = np.array([[3,4],[5,6]])
wektor = np.array([2,3])


# Inner product of matrices
#[[1*3+2*5  1*4+2*6], [10*3+20*5 10*4+20*6]
#[13, 16][130, 160]
print(np.dot(x, y))


# Matrix / vector product; produce the rank 1 array [8 80]
#[[2*1+3*2], [2*10 + 3*20]
#[8, 80]
print(np.dot(x, wektor))

[[ 13  16]
 [130 160]]
[ 8 80]


In [19]:
x


array([[ 1,  2],
       [10, 20]])

In [20]:
y

array([[3, 4],
       [5, 6]])