In [6]:
import numpy as np

# Importujemy bibliotekę numpy (operacje na macierzach)

# Programowujemy naszą sieć z wykorzystaniem numpy

In [ ]:
import numpy as np

#funkcja aktywacyjna i jej pochodna
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [ ]:
def sigmoid_pochodna(x):
    return x * (1-x)

In [ ]:
#funkcje potrzebne do stworzenia sieci
def hidden(j):
    return sigmoid(np.dot(dane[j],Input_Wagi))

In [ ]:
def answer(j):
    return sigmoid(np.dot(hidden(j),Hidden_Wagi))

In [ ]:
def wagi(seed=True):
    #ustalamy seed, zeby eksperyment byl powtarzalny
    if seed:
        np.random.seed(3)
    #tworzyny losowe wagi za pomoca funkcji numpy (zwraca wartosc pomiedzy 0 i 1)
    Input_Wagi = 2*np.random.random((2,4)) - 1
    Hidden_Wagi = 2*np.random.random((4)) - 1
    return Input_Wagi, Hidden_Wagi

In [3]:
Input_Wagi, Hidden_Wagi = wagi()

print(f'Input_Wagi:\n {Input_Wagi}')
print(f'Hidden_Wagi:\n {Hidden_Wagi}')

Input_Wagi:
 [[ 0.10159581  0.41629565 -0.41819052  0.02165521]
 [ 0.78589391  0.79258618 -0.74882938 -0.58551424]]
Hidden_Wagi:
 [-0.89706559 -0.11838031 -0.94024758 -0.08633355]


# Uczymy naszą sieć

In [ ]:
#nasze dane    
dane = np.array([[0,0],
                 [0,1],
                 [1,0],
                 [1,1]])

odpowiedz = np.array([[0],
                      [1],
                      [0],
                      [0]])

In [ ]:
epoki = 1000

In [22]:
Input_Wagi, Hidden_Wagi = wagi()

def learn(dane, odpowiedz, Input_Wagi, Hidden_Wagi, epoki, verbose):
    
    errors =  []
    
    for epoch in range(epoki):
        for j in range(4):
            odp = answer(j)
            #print(f' answer: {odp}')
            
            err = []

            answer_error = odpowiedz[j] - odp
            err.append(answer_error)
            
            #print(f'answer error: {answer_error}')
            answer_delta = answer_error*sigmoid_pochodna(odp)
            #print(f'answer_delta: {answer_delta}')
            hidden_error = answer_delta * Hidden_Wagi.T
            #print(f'hidden_error: {hidden_error}')

            hidden_delta = hidden_error * sigmoid_pochodna(hidden(j))
            #print(f'hidden_delta: {hidden_delta}')

            Hidden_Wagi += hidden(j) * (answer_delta)
            #print(f'Hidden_Wagi : {Hidden_Wagi}')

            Input_Wagi += dane[j].reshape(2, 1) * (hidden_delta)
            
            if j == 3:
                err = [abs(i) for i in err]
                errors.append(err)


        if verbose == 1:
            if epoch%(100) == 0:
                for i in range(4):
                    print(f'dane: {dane[i]} odpowiedz: {odpowiedz[i]} odpowiedz_sieci: {answer(i)}')
                print(errors[-1])
                print('-------------------------------------------------------------------')

    return Input_Wagi, Hidden_Wagi

In [30]:
learn(dane, odpowiedz, Input_Wagi, Hidden_Wagi, epoki, verbose = 0)

#decibel value , average error for epoch

(array([[ 2.49095656, -2.04877051,  4.38074116,  2.29667811],
        [-2.33441008,  2.82091806, -3.05313302, -2.47101885]]),
 array([-3.69649828,  5.58970631, -6.83305818, -3.88340635]))

In [27]:
dobre_wagi = learn(dane, odpowiedz, Input_Wagi, Hidden_Wagi, epoki, 0)

In [88]:
dobre_wagi

(array([[-5.420739  ,  1.36329638,  0.4410503 ,  0.87714009],
        [ 2.10091446,  0.96140039, -3.18904679, -3.80009574]]),
 array([-7.50594725,  4.66076789, -6.23295884, -5.35307276]))

In [90]:
def siec(dobre_wagi, dane):
    
    def sigmoid(x):
        return 1/(1+np.exp(-x))

    def hidden(dane):
        return sigmoid(np.dot(dane,dobre_wagi[0]))

    return sigmoid(np.dot(hidden(dane),dobre_wagi[1]))

    

In [93]:
dane = [0, 1]
siec(dobre_wagi, dane)

0.024603593353301326